jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
      with:
        fetch-depth: '0'
        ref: docs
    - continue-on-error: true
      uses: actions/setup-node@v4
      with:
        cache: npm
        node-version: 20
    - continue-on-error: true
      run: npm ci
    - continue-on-error: true
      name: Build
      run: npm run docs:build
    - continue-on-error: true
      name: Deploy
      uses: peaceiris/actions-gh-pages@main
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/.vitepress/dist
    - continue-on-error: true
      env:
        GITEE_AUTH: ${{ secrets.GITEE_AUTH }}
      if: ${{ env.GITEE_AUTH != ''}}
      name: Sync Push to Gitee
      run: 'echo "https://$GITEE_AUTH@gitee.com/" > .credential

        git config --local credential.helper "store --file=.credential"

        git remote add gitee https://gitee.com/NiceLeee/BilibiliDown.git

        branch_name=`git rev-parse --abbrev-ref HEAD`

        # git fetch --unshallow origin "$branch_name"

        git push -f gitee "$branch_name"

        rm -f .credential

        '
    - continue-on-error: true
      env:
        BITBUCKET_TOKEN: ${{ secrets.BITBUCKET_TOKEN }}
      if: ${{ env.BITBUCKET_TOKEN != ''}}
      name: Sync Push to Bitbucket
      run: 'echo "https://x-token-auth:$BITBUCKET_TOKEN@bitbucket.org/" > .credential

        git config --local credential.helper "store --file=.credential"

        git remote add bitbucket https://bitbucket.org/niceleeee/bilibilidown.git

        branch_name=`git rev-parse --abbrev-ref HEAD`

        # git fetch --unshallow origin "$branch_name"

        git push -f bitbucket "$branch_name"

        rm -f .credential'
name: Deploy Document
on:
  repository_dispatch:
    types: trigger-ga___document.yml
