jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
      with:
        ref: dev
    - continue-on-error: true
      name: Set up JDK 1.8
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: '8'
    - continue-on-error: true
      env:
        BUILD_TYPE: Beta
      id: tag_latest
      name: Read tag_latest and Save build info
      run: 'python ./.github/scripts/read_version_and_save_build_info.py

        '
    - continue-on-error: true
      name: Package Jar
      run: 'chmod +x package.sh

        ./package.sh

        chmod +x .github/scripts/package_launcher.sh

        ./.github/scripts/package_launcher.sh

        '
    - continue-on-error: true
      env:
        VERSION_NUMBER: ${{ steps.tag_latest.outputs.value }}
      name: ZIP files
      run: 'chmod +x .github/scripts/gen_zip_for_pre_release.sh

        ./.github/scripts/gen_zip_for_pre_release.sh

        '
    - continue-on-error: true
      name: Upload artifacts(no jre)
      uses: actions/upload-artifact@v4
      with:
        name: BilibiliDown.v${{steps.tag_latest.outputs.value}}.pre-release
        path: ./BilibiliDown.v${{steps.tag_latest.outputs.value}}.pre-release.zip
name: Build Pre Release
on:
  repository_dispatch:
    types: trigger-ga___pre-release-artifacts.yml
